version: '3.7'
services:
  reverseproxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    restart: always

  container1:
    depends_on:
      - reverseproxy
    image: cloudexpart/jsarkar-devops:latest
    # ports: 
    #   - 9090
    restart: always

      


  